apps/customer/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required
from .views import *


app_name = 'customer'

urlpatterns = [
    path('', login_required(HomeCustomer.as_view()), name="home"),
    path('createpet', login_required(CreatePetView.as_view()), name="createpet"),
    path('udpatepet/<int:pk>', login_required(UpdatePetView.as_view()), name="updatepet"),
    path('deletepet/<int:pk>', login_required(DeletePetView.as_view()), name="deletepet"),
    path('contractService/<int:pk>', login_required(ContractServiceView.as_view()), name="contractservice"),
    path('myorders', login_required(MyOrdersView.as_view()), name="myorders"),
    path('generate-bill/<int:order>', login_required(GenerateBillView.as_view()), name="generatebill"),
]

mascotas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.core.urls')),
    path('admin/', admin.site.urls),
    path('authenticate/', include('apps.authenticate.urls')),
    path('colaborator/', include('apps.colaborator.urls')),
    path('customer/', include('apps.customer.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/customer/models.py
from django.db import models
from django.conf import settings
from apps.core.models import *
# Create your models here.
class Pet(models.Model):
    name = models.CharField(max_length=255)
    edad = models.PositiveSmallIntegerField()
    pet_image = models.ImageField(upload_to='pets/')
    pet_type = models.ForeignKey(TypePet, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    

class Order(models.Model):
    STATUS_ORDER = [
        ('request', 'Solicitado'),
        ('waitpayment', 'Esperando pago'),
        ('rejected', 'Rechazado'),
        ('cancelled', 'Cancelado'),
        ('ready', 'Listo para iniciar'),
        ('inprogress', 'Iniciado'),
        ('revertPay', 'Declinado, reversar pago'),
        ('finalized', 'Finalizado')
    ]
    price = models.PositiveIntegerField()
    utility = models.PositiveIntegerField(default=0, editable=False)
    datetime_booking = models.DateTimeField()
    hours_contract = models.PositiveIntegerField(default=1)
    datetime_finally = models.DateTimeField(blank=True, null=True)
    status = models.CharField(max_length=255, blank=False, choices=STATUS_ORDER)
    score = models.FloatField(blank=True, null=True)
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    service = models.ForeignKey(ServicePerColaborator, on_delete=models.CASCADE, default=1)
    is_payment = models.BooleanField(blank=True, null=True)
    payment_date = models.DateTimeField(blank=True, null=True)

    def calculate_utility(self):
        if self.status == 'finalized':
            return int(self.price * 0.15)
        else:
            return 0

    def save(self,*args,**kwargs):
        self.utility = self.calculate_utility()
        super().save(*args, **kwargs)

    def __str__(self):
        return "Num order %s" % (self.pk)

apps/customer/forms.py
from django import forms
from .models import Pet, Order

class PetForm(forms.ModelForm):
    class Meta():
        model = Pet
        fields = ('name','edad','pet_image', 'pet_type')
        exclude = ['owner']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Nombre','class':'form-control'}),
            'edad': forms.NumberInput(attrs={'placeholder': 'Edad','class':'form-control'}),
            'pet_type': forms.Select(attrs={'class':'form-control'}),
        }
        labels = {
            'name': "Nombre",
            'edad': "Edad",
            'pet_type': "Tipo de mascota"
        }

class OrderForm(forms.ModelForm):
    class Meta():
        model = Order
        fields = ('datetime_booking','hours_contract')
        widgets = {
            'datetime_booking': forms.DateInput(attrs={'placeholder': 'Fecha de contratacion','class':'form-control booking'}),
            'hours_contract': forms.NumberInput(attrs={'placeholder': 'Horas a contratar','class':'form-control hours_contract'}),
        }
        labels = {
            'datetime_booking': "Fecha agendamiento",
            'hours_contract': "Horas de contratación",
        }

apps/customer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import FormView, TemplateView, RedirectView, View, CreateView, UpdateView, DeleteView, ListView
from django.urls import reverse
from .models import *
from apps.core.models import *
from .forms import *
from django.core.exceptions import ValidationError
from django.contrib import messages 
import datetime, datetime
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4, letter
# Create your views here.

class HomeCustomer(TemplateView):
    template_name = "mis-mascotas.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pets'] = Pet.objects.filter(owner = self.request.user)
        return context

class CreatePetView(CreateView):
    model = Pet
    form_class=PetForm
    template_name = 'petmanage.html'
    
    def get_success_url(self):
        return reverse('customer:home')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user

        try:
            self.object.full_clean()
        except ValidationError:
            return super(CreatePetView, self).form_invalid(form)
        return super(CreatePetView, self).form_valid(form)

class UpdatePetView(UpdateView):
    model = Pet
    form_class=PetForm
    template_name = 'petmanage.html'
    
    def get_success_url(self):
        return reverse('customer:home')


class DeletePetView(DeleteView):
    model = Pet
    
    def get(self, request, pk):
        service = get_object_or_404(Pet, pk=pk)
        service.delete()
        return redirect(reverse('customer:home'))

class ContractServiceView(View):
    def get(self, request, *args, **kwargs):
        typePay = {
            'hours':'Horas',
            'full':'Tarifa unica',
        }
        pet = get_object_or_404(Pet, pk=kwargs['pk'])
        queryset = ServicePerColaborator.objects.filter(pet_types=pet.pet_type)
        return render(request,'contract.html',{'object_list':queryset, 'typePay':typePay, 'formcontact':OrderForm, 'pet':pet})
    
    def post(self, request, *args, **kwargs):
        service = get_object_or_404(ServicePerColaborator, pk=request.POST.get('id_service'))
        pet = get_object_or_404(Pet, pk=request.POST.get('id_pet'))
        newOrder = Order(datetime_booking=request.POST.get('datetime_booking'), status="request", pet=pet, service=service)
        if service.rate_type == 'full':
            newOrder.price = service.rate
        else:
            newOrder.hours_contract = int(request.POST.get('hours_contract'))
            newOrder.price = service.rate * int(request.POST.get('hours_contract'))
        newOrder.save()
        messages.add_message(request, messages.SUCCESS, "Orden creada exitosamente, si desea ver su estado Mis ordenes brindara toda la información.")
        return redirect(reverse('customer:contractservice', kwargs={'pk': pet.id}))

class MyOrdersView(View):
    def get(self, request, *args, **kwargs):
        ordersPerType = []
        for key, value in Order.STATUS_ORDER: 
            if key == 'request':
                headers = ['#','Servicio','Agendada','Precio','Mascota','Acciones']
                spanactions = 1
            if key == 'waitpayment':
                headers = ['#','Servicio','Agendada','Precio','Mascota','Acciones']
                spanactions = 2
            if key == 'cancelled':
                headers = ['#','Servicio','Agendada','Precio','Mascota']
                spanactions = 0
            if key == 'rejected':
                headers = ['#','Servicio','Mascota']
                spanactions = 0
            if key == 'ready':
                headers = ['#','Servicio','Agendada','Mascota', 'Acciones']
                spanactions = 2
            if key == 'inprogress':
                headers = ['#','Servicio','Agendada','Mascota']
                spanactions = 2
            if key == 'revertPay':
                headers = ['#','Servicio','Mascota']
                spanactions = 2
            if key == 'finalized':
                headers = ['#','Servicio','Agendada','Precio','Mascota','Acciones','Puntua']
                spanactions = 2
            orders = {
                'status': key,
                'legend': value,
                'headers': headers,
                'spanactions': spanactions,
                'orders': Order.objects.filter(status=key, pet__owner=request.user).order_by('id')
            }
            ordersPerType.append(orders)
        context = {'orderstype':ordersPerType}
        return render(request,'customer/myorders.html',context)
    
    def post(self, request, *args, **kwargs):
        order= get_object_or_404(Order, pk=request.POST.get('id'), pet__owner=request.user)
        order.status = request.POST.get('status')
        print(request.POST)
        if order.status == 'ready':
            order.is_payment = True
            order.payment_date = datetime.datetime.now()

        if order.status == 'finalized':
            print(request.POST.get('rating%s' % order.id))
            order.score = request.POST.get('rating%s' % order.id)
            order.datetime_finally = datetime.datetime.now()
        order.save()
        return redirect(reverse('customer:myorders'))

class GenerateBillView(View):
    def get(self, request, *args, **kwargs):
        order= get_object_or_404(Order, pk=kwargs['order'], pet__owner=request.user)
        w, h = letter
        # Create a file-like buffer to receive PDF data.
        buffer = io.BytesIO()

        # Create the PDF object, using the buffer as its "file."
        p = canvas.Canvas(buffer)
        text = p.beginText(50, h - 50)
        # Draw things on the PDF. Here's where the PDF generation happens.
        # See the ReportLab documentation for the full list of functionality.
        text.textLine("Factura # %s"% kwargs['order'])
        text.textLine("Servicio: %s" % order.service.service.name)
        text.textLine("Mascota: %s" % order.pet.name)
        text.textLine("Fecha de servicio: %s" % order.datetime_booking)
        text.textLine("Fecha de servicio: %s" % order.datetime_booking)
        text.textLine("Fecha de pago: %s" % order.payment_date)
        text.textLine("Precio: %s" % order.price)
        text.textLine("Pagado por: %s %s" % (order.pet.owner.first_name,order.pet.owner.last_name))
        p.drawText(text)
        # Close the PDF object cleanly, and we're done.
        p.showPage()
        p.save()

        # FileResponse sets the Content-Disposition header so that browsers
        # present the option to save the file.
        buffer.seek(0)
        return FileResponse(buffer, as_attachment=True, filename='factura%s.pdf' % kwargs['order'])

apps/customer/templates/customer/myorders.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% block menu  %}
    {% include "partials/_menu_customer.html" %}
{% endblock menu %}
{% block styles %}
    <link href="{% static '/css/starts.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> {# Adds date-picker required JS and CSS #}
{% endblock styles %}
{% block content %}
<div class="container">  
    {% for typeorder in orderstype %}
    <div class="row mt-5">
        <div class="col-10 offset-1">
            <fieldset class="border p-2">
                <legend class="scheduler-border">{{ typeorder.legend }}</legend>
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            {% for header in typeorder.headers %}
                                {% if header == 'Acciones' %}
                                <th scope="col" colspan="{{ typeorder.spanactions }}">{{ header }}</th>
                                {% else %}
                                <th scope="col">{{ header }}</th>
                                {% endif %}
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody>
                        {% if typeorder.status == 'request' %}
                            {% if typeorder.orders.count > 0 %}
                                {% for order in typeorder.orders %}
                                    <form method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="id" value="{{ order.id }}" />
                                        <tr>
                                            <th scope="row">{{ order.id }}</th>
                                            <td>{{ order.service.service.name }}</td>
                                            <td>{{ order.datetime_booking }}</td>
                                            <td>{{ order.price|intcomma  }}</td>
                                            <td>{{ order.pet.name }}</td>
                                            <td><button type="submit" class="btn btn-danger" name="status" value="cancelled">Cancelar</button></td>
                                        </tr>
                                    </form>
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="{{ typeorder.headers|length }}">No encontramos registros asociados</td>
                                </tr>
                            {% endif %}
                        {% elif typeorder.status == 'waitpayment' %}
                            {% if typeorder.orders.count > 0 %}
                                {% for order in typeorder.orders %}
                                    <form method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="id" value="{{ order.id }}" />
                                        <tr>
                                            <th scope="row">{{ order.id }}</th>
                                            <td>{{ order.service.service.name }}</td>
                                            <td>{{ order.datetime_booking }}</td>
                                            <td>{{ order.price|intcomma  }}</td>
                                            <td>{{ order.pet.name }}</td>
                                            <td><button type="submit" class="btn btn-danger" name="status" value="cancelled">Cancelar</button></td>
                                            <td><button type="submit" class="btn btn-success" name="status" value="ready">Pagar</button></td>
                                        </tr>
                                    </form>
                                {% endfor %}
                            {% else %}
                                <tr>   
                                    <td colspan="{{ typeorder.headers|length }}">No encontramos registros asociados</td>
                                </tr>
                            {% endif %}
                        {% elif typeorder.status == 'cancelled' %}
                            {% if typeorder.orders.count > 0 %}
                                {% for order in typeorder.orders %}
                                    <tr>
                                        <th scope="row">{{ order.id }}</th>
                                        <td>{{ order.service.service.name }}</td>
                                        <td>{{ order.datetime_booking }}</td>
                                        <td>{{ order.price|intcomma  }}</td>
                                        <td>{{ order.pet.name }}</td>
                                    </tr>
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="{{ typeorder.headers|length }}">No encontramos registros asociados</td>
                                </tr>
                            {% endif %}
                        {% elif typeorder.status == 'rejected' %}
                            {% if typeorder.orders.count > 0 %}
                                {% for order in typeorder.orders %}
                                    <tr>
                                        <th scope="row">{{ order.id }}</th>
                                        <td>{{ order.service.service.name }}</td>
                                        <td>{{ order.pet.name }}</td>
                                    </tr>
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="{{ typeorder.headers|length }}">No encontramos registros asociados</td>
                                </tr>
                            {% endif %}
                        {% elif typeorder.status == 'ready' %}
                            {% if typeorder.orders.count > 0 %}
                                {% for order in typeorder.orders %}
                                    <tr>
                                        <th scope="row">{{ order.id }}</th>
                                        <td>{{ order.service.service.name }}</td>
                                        <td>{{ order.datetime_booking }}</td>
                                        <td>{{ order.pet.name }}</td>
                                        <td><a href="{% url 'customer:generatebill' order=order.id %}"><i class="fas fa-fw fa-file-pdf"></i></a></td>
                                        <td><button type="submit" class="btn btn-danger" name="status" value="revertPay">Reversar pago</button></td>
                                    </tr>
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="{{ typeorder.headers|length }}">No encontramos registros asociados</td>
                                </tr>
                            {% endif %}
                        {% elif typeorder.status == 'inprogress' %}
                            {% if typeorder.orders.count > 0 %}
                                {% for order in typeorder.orders %}
                                    <tr>
                                        <th scope="row">{{ order.id }}</th>
                                        <td>{{ order.service.service.name }}</td>
                                        <td>{{ order.datetime_booking }}</td>
                                        <td>{{ order.pet.name }}</td>
                                    </tr>
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="{{ typeorder.headers|length }}">No encontramos registros asociados</td>
                                </tr>
                            {% endif %}
                        {% elif typeorder.status == 'revertPay' %}
                            {% if typeorder.orders.count > 0 %}
                                {% for order in typeorder.orders %}
                                    <tr>
                                        <th scope="row">{{ order.id }}</th>
                                        <td>{{ order.service.service.name }}</td>
                                        <td>{{ order.pet.name }}</td>
                                    </tr>
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="{{ typeorder.headers|length }}">No encontramos registros asociados</td>
                                </tr>
                            {% endif %}
                        {% elif typeorder.status == 'finalized' %}
                            {% if typeorder.orders.count > 0 %}
                                {% for order in typeorder.orders %}
                                    <tr>
                                        <th scope="row">{{ order.id }}</th>
                                        <td>{{ order.service.service.name }}</td>
                                        <td>{{ order.datetime_booking }}</td>
                                        <td>{{ order.price|intcomma  }}</td>
                                        <td>{{ order.pet.name }}</td>
                                        <td><td><a href="{% url 'customer:generatebill' order=order.id %}"><i class="fas fa-fw fa-file-pdf"></i></a></td></td>
                                        <td>
                                            <form method="post">
                                                {% csrf_token %}
                                                <input type="hidden" name="id" value="{{ order.id }}" />
                                                <input type="hidden" name="status" value="{{ order.status }}" />
                                                <div class="rating mr-5">
                                                    <input type="radio" id="star5_{{ order.id }}" name="rating{{ order.id }}" value="5" {% if order.score == 5 %}checked disabled{% endif %}/><label for="star5_{{ order.id }}" title="Cinco estrellas">5 stars</label>
                                                    <input type="radio" id="star4_{{ order.id }}" name="rating{{ order.id }}" value="4" {% if order.score == 4 %}checked disabled{% endif %}/><label for="star4_{{ order.id }}" title="Cuatro estrellas">4 stars</label>
                                                    <input type="radio" id="star3_{{ order.id }}" name="rating{{ order.id }}" value="3" {% if order.score == 3 %}checked disabled{% endif %}/><label for="star3_{{ order.id }}" title="Tres estrellas">3 stars</label>
                                                    <input type="radio" id="star2_{{ order.id }}" name="rating{{ order.id }}" value="2" {% if order.score == 2 %}checked disabled{% endif %}/><label for="star2_{{ order.id }}" title="Dos estrellas">2 stars</label>
                                                    <input type="radio" id="star1_{{ order.id }}" name="rating{{ order.id }}" value="1" {% if order.score == 1 %}checked disabled{% endif %}/><label for="star1_{{ order.id }}" title="Uno estrellas">1 star</label>
                                                </div>
                                                {% if order.score is None %}
                                                    <button type="submit" class="btn btn-primary">Calificar</button>
                                                {% endif %}
                                            </form>
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="{{ typeorder.headers|length }}">No encontramos registros asociados</td>
                                </tr>
                            {% endif %}
                        {% endif %}
                    </tbody>
                </table>
            </fieldset>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

{% block scripts %}
 
{% endblock scripts %}