apps/colaborator/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required
from .views import *


app_name = 'colaborator'

urlpatterns = [
    path('', login_required(HomecolaboratorView.as_view()), name="home"),
    path('orders', login_required(OrdersColaboboratorView.as_view()), name="orders"),
    path('myservices', login_required(ServicesColaboratorView.as_view()), name="myservices"),
    path('assingservice', login_required(CreateServiceColaboratorView.as_view()), name="assingservice"),
    path('service/<int:pk>', login_required(UpdateServiceColaboratorView.as_view()), name="updateservice"),
    path('servicedelete/<int:pk>', login_required(DeleteServiceColaboratorView.as_view()), name="deleteservice")
]

mascotas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.core.urls')),
    path('admin/', admin.site.urls),
    path('authenticate/', include('apps.authenticate.urls')),
    path('colaborator/', include('apps.colaborator.urls')),
    path('customer/', include('apps.customer.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/colaborator/models.py
from django.db import models

# Create your models here.

class Colaborator(models.Model):
    idPerson   = models.IntegerField()
    name = models.CharField(max_length=50)
    mail = models.EmailField()
    experience = models.TextField()
    phone = models.CharField(max_length=12)
    address = models.TextField()
    qualification = models.IntegerField(default=5)
    date_of_birth = models.DateField()                    

apps/colaborator/forms.py
from django import forms
from apps.core.models import *

class ServicePerColaboratorForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(ServicePerColaboratorForm, self).__init__(*args, **kwargs)

    class Meta:
        model = ServicePerColaborator
        exclude = ['colaborator']

        fields = ('coverage_city', 'rate_type', 'pet_types', 'rate', 'description', 'service')
        widgets = {
            'coverage_city': forms.Select(attrs={
                'placeholder': 'Ciudad de cobertura',
                'class':'form-control'
            }),
            'rate_type': forms.Select(attrs={
                'placeholder': 'Ciudad de cobertura',
                'class':'form-control'
            }),
            'pet_types': forms.CheckboxSelectMultiple(attrs={
                
            }),
            'rate': forms.TextInput(attrs={
                'type' : 'text',
                'placeholder': 'Tarifa',
                'class':'form-control'
            }),
            'description': forms.Textarea(attrs={
                'class':'form-control',
                'placeholder': "Describa su servicio"
            }),
            'service': forms.Select(attrs={
                'placeholder': 'Servicio',
                'class':'form-control'
            }),
        }
        labels = {
            'coverage_city': "Ciudad de cobertura",
            'rate_type': "Tipo de cobro",
            'pet_types': "Tipo de mascota",
            'rate': "Tarifa",
            'description': "Descripción",
            'service': "Servicio",
        }

apps/colaborator/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views import View
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy, reverse
from apps.core.models import *
from apps.customer.models import *
from .forms import *
import datetime, datetime
from django.db.models import F
from django.db.models import Count, Sum
from django.db import connection
from django.core.exceptions import ValidationError
# Create your views here.

class HomecolaboratorView(TemplateView):
    template_name = "dashboard-collaborator.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = datetime.date.today()
        day = (today.weekday() + 6) % 7 #0 Dom #1 Lun #2 Mar...
        lastpay = today - datetime.timedelta(day)
        lastpay = datetime.datetime.combine(lastpay, datetime.time.min)  
        today = datetime.datetime.combine(today, datetime.time.max)  
        orders = Order.objects.filter(datetime_finally__range=(lastpay, today), service__colaborator=self.request.user, status='finalized').annotate(payColaborator=F('price') - F('utility'))
        newOrders = Order.objects.filter(service__colaborator=self.request.user, status='request').count()
        today_min = datetime.datetime.combine(datetime.date.today(), datetime.time.min)
        today_max = datetime.datetime.combine(datetime.date.today(), datetime.time.max)
        todayOrders = Order.objects.filter(service__colaborator=self.request.user, datetime_booking__range=(today_min, today_max), status='ready').annotate(payColaborator=F('price') - F('utility')).count()
        with connection.cursor() as cursor:
            queryToGraph = """select distinct(DATE(customer_order.datetime_finally)),sum(customer_order.price-customer_order.utility) 
                                from customer_order inner join core_servicepercolaborator on customer_order.service_id = core_servicepercolaborator.id 
                                where customer_order.status='finalized' 
                                and core_servicepercolaborator.colaborator_id = %s
                                group by DATE(customer_order.datetime_finally)
                                order by date ASC""" % self.request.user.id
            cursor.execute(queryToGraph)
            context["dataGraphic"] = cursor.fetchall()
        
        context["ordersThisWeek"] = orders
        context["countNewOrders"] = newOrders
        context["countTodayOrders"] = todayOrders
        context["time"] = datetime.datetime.now()
        return context

class OrdersColaboboratorView(ListView):
    def get_queryset(self, **kwargs):
        if 'filter' in self.request.GET:
            fil = self.request.GET.get('filter')
            if fil == 'news':
                queryset = Order.objects.filter(service__colaborator=self.request.user, status='request').annotate(payColaborator=F('price') - F('utility'))
            elif fil == 'today':
                today_min = datetime.datetime.combine(datetime.date.today(), datetime.time.min)
                today_max = datetime.datetime.combine(datetime.date.today(), datetime.time.max)
                queryset = Order.objects.filter(service__colaborator=self.request.user, datetime_booking__range=(today_min, today_max)).annotate(payColaborator=F('price') - F('utility')).order_by('id')
        else:
            queryset = Order.objects.filter(service__colaborator=self.request.user).order_by('status').annotate(payColaborator=F('price') - F('utility'))
        return queryset
    
    def get_context_data(self, **kwargs):
        statusOrders = {
            'request':'Solicitado',
            'accepted':'Aceptado',
            'waitpayment':'Esperando pago',
            'rejected':'Rechazado',
            'ready': 'Listo para iniciar',
            'expired':'Expirado',
            'inprogress':'Iniciado',
            'revertPay': 'Declinado, reversar pago',
            'finalized':'Finalizado'
        }
        context = super().get_context_data(**kwargs)
        context["titleTable"] = "test"
        context["status"] = statusOrders
        context["time"] = datetime.datetime.now()
        return context
    
    def post(self, request, *args, **kwargs):
        queryget = ""
        if 'filter' in self.request.GET:
            queryget = "?filter=%s" % self.request.GET.get('filter')       

        order= get_object_or_404(Order, pk=request.POST.get('id'), service__colaborator=request.user)
        order.status = request.POST.get('status')
        if order.status == 'finalized':
            order.datetime_finally = datetime.datetime.now()
        order.save()
        return redirect(reverse('colaborator:orders') + queryget)

class ServicesColaboratorView(ListView):
    template_name = 'myservices.html'
    paginate_by = 15
    def get_queryset(self):
        queryset = ServicePerColaborator.objects.filter(colaborator=self.request.user).order_by('id')
        return queryset

    def get_context_data(self, **kwargs):
        typePay = {
            'hours':'Horas',
            'full':'Tarifa unica',
        }
        context = super(ServicesColaboratorView, self).get_context_data(**kwargs)
        context["typePay"] = typePay
        context["time"] = datetime.datetime.now()
        return context

class CreateServiceColaboratorView(SuccessMessageMixin, CreateView):
    model = ServicePerColaborator
    form_class = ServicePerColaboratorForm
    template_name = 'servicecolaborator.html'
    success_message = '¡Se ha asignado un nuevo servicio en su cuenta!'
    
    def get_success_url(self):
        return reverse('colaborator:myservices')
    
    def get_context_data(self, **kwargs):
        context = super(CreateServiceColaboratorView, self).get_context_data(**kwargs)
        context["time"] = datetime.datetime.now()
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.colaborator = self.request.user

        try:
            self.object.full_clean()
        except ValidationError:
            #raise ValidationError("No can do, you have used this name before!")
            #return self.form_invalid(form)
            form._errors["service"] = "Este servicio ya esta siendo prestado por ud. por favor edite su actual servicio."
            return super(CreateServiceColaboratorView, self).form_invalid(form)
        return super(CreateServiceColaboratorView, self).form_valid(form)
    
class UpdateServiceColaboratorView(UpdateView):
    model = ServicePerColaborator
    form_class = ServicePerColaboratorForm
    template_name = 'servicecolaborator.html'
    success_message = '¡Se ha actualizado el servicio en su cuenta!'
    
    def get_success_url(self):
        return reverse('colaborator:myservices')

class DeleteServiceColaboratorView(DeleteView):
    model = ServicePerColaborator
    
    def get(self, request, pk):
        service = get_object_or_404(ServicePerColaborator, pk=pk)
        service.delete()
        return redirect(reverse('colaborator:myservices'))

apps/colaborator/templates/createservicecolaborator.html
{% extends "colaborator/base.html" %}
{% load static %}
{% load humanize %}
{% load utilities %}
{% block styles %}
<link href="{% static '/css/colaborator.css' %}" rel="stylesheet">
{% endblock styles %}
{% block content %}
      <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
          </li>
          <li class="breadcrumb-item active">Asignando servicios</li>
        </ol>
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-plus-square"></i> Asignar servicio
            </div>
          <div class="card-body">
            <div class="col col-sm-12 col-md-8 offset-md-2">
              <form method="post" novalidate>
                  {% csrf_token %}
                  {% for field in form %}
                  <div class="form-group row">
                    <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-10">
                      {{ field }}
                      <span class="text-danger">{{ field.errors|striptags }}</span>
                    </div>
                  </div>
                  {% endfor %}
                  <div class="float-right">
                    <a href="{% url 'colaborator:myservices' %}"><button type="button" class="btn btn-danger">Cancelar</button></a>
                    <button type="submit" class="btn btn-primary">Guardar</button>
                  </div>
              </form>
            </div>
          </div>
          <div class="card-footer small text-muted"><b>Nota:</b> Si considera que puede prestar un nuevo servicio que no esta listado y desea proponerlo, por favor envie un correo con una breve descripción a <a href="mailto:admin@dogenest.com">admin@dogenest.com</a></div>
        </div>
      </div>
{% endblock content %}

{% block scripts %}
<!-- Core plugin JavaScript-->
<script src="{% static '/js/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Page level plugin JavaScript-->
<script src="{% static '/js/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static '/js/datatables/dataTables.bootstrap4.js' %}"></script>


<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin/sb-admin.min.js' %}"></script>
<script>
  var ejeX = []
  var ejeY = []
  var may = 0
  {% for gain in dataGraphic %}
    var val = {{ gain.1 }}
    ejeX.push("{{ gain.0|date:'D d M' }}")
    ejeY.push(val)
    if (may < val){
      may = val;
    }
  {% endfor %}
</script>
<!-- Demo scripts for this page-->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>
{% endblock scripts %}

apps/colaborator/templates/dashboard-collaborator.html
{% extends "colaborator/base.html" %}
{% load static %}
{% load humanize %}

{% block styles %}
<link href="{% static '/css/colaborator.css' %}" rel="stylesheet">
{% endblock styles %}
{% block content %}
      <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
          </li>
          <li class="breadcrumb-item active">Info</li>
        </ol>

        <!-- Icon Cards-->
        <div class="row">
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-success o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fas fa-fw fa-shopping-cart"></i>
                </div>
                <div class="mr-5">{{countNewOrders}} {% if countNewOrders == 1 %}Nueva orden!{% endif %}{% if countNewOrders is not 1 %}Nuevas ordenes!{% endif %}</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="{% url 'colaborator:orders' %}?filter=news">
                <span class="float-left">Ver Detalles</span>
                <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-primary o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fas fa-fw fa-calendar-check"></i>
                </div>
                <div class="mr-5">{{countTodayOrders}} Ordenes hoy</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="{% url 'colaborator:orders' %}?filter=today">
                <span class="float-left">Ver detalles</span>
                <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-warning o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fas fa-fw fa-list"></i>
                </div>
                <div class="mr-5">Historico de ordenes</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="{% url 'colaborator:orders' %}">
                <span class="float-left">Ver detalles</span>
                <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-danger o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fas fa-fw fa-handshake"></i>
                </div>
                <div class="mr-5">Mis servicios</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="{% url 'colaborator:myservices' %}">
                <span class="float-left">Ver mis servicios</span>
                <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
        </div>

        <!-- Area Chart Example-->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-chart-area"></i>
            Grafico de mis ganancias</div>
          <div class="card-body">
            <canvas id="myAreaChart" width="100%" height="30"></canvas>
          </div>
          <div class="card-footer small text-muted">Actualizado {{time}}</div>
        </div>

        <!-- DataTables Example -->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-table"></i>
            Ordenes finalizadas para pago proximo martes</div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Agendada</th>
                    <th>Fecha finalización</th>
                    <th>Precio</th>
                    <th>Tu ganancia</th>
                    <th>Servicio</th>
                    <th>Puntuación</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>ID</th>
                    <th>Agendada</th>
                    <th>Fecha finalización</th>
                    <th>Precio</th>
                    <th>Tu ganancia</th>
                    <th>Servicio</th>
                    <th>Puntuación</th>
                  </tr>
                </tfoot>
                <tbody>
                  {% for service in ordersThisWeek %}
                  <tr>
                    <td>{{ service.id }}</td>
                    <td>{{ service.datetime_booking|date:"D d M Y" }}</td>
                    <td>{{ service.datetime_finally|date:"D d M Y" }}</td>
                    <td>$ {{ service.price|intcomma }}</td>
                    <td>$ {{ service.payColaborator|intcomma }}</td>
                    <td>{{ service.service.service.name }}</td>
                    <td>
                      <div class="rating">
                        <input type="radio" id="{{ service.id }}star5" name="rating{{ service.id }}" value="5" {% if service.score == 5 %}checked{% endif %}  disabled="disabled"/><label for="star5" title="Cinco estrellas">5 stars</label>
                        <input type="radio" id="{{ service.id }}star4" name="rating{{ service.id }}" value="4" {% if service.score == 4 %}checked{% endif %}  disabled="disabled"/><label for="star4" title="Cuatro estrellas">4 stars</label>
                        <input type="radio" id="{{ service.id }}star3" name="rating{{ service.id }}" value="3" {% if service.score == 3 %}checked{% endif %} disabled="disabled"/><label for="star3" title="Tres estrellas">3 stars</label>
                        <input type="radio" id="{{ service.id }}star2" name="rating{{ service.id }}" value="2" {% if service.score == 2 %}checked{% endif %} disabled="disabled"/><label for="star2" title="Dos estrellas">2 stars</label>
                        <input type="radio" id="{{ service.id }}star1" name="rating{{ service.id }}" value="1" {% if service.score == 1 %}checked{% endif %} disabled="disabled"/><label for="star1" title="Uno estrellas">1 star</label>
                      </div>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
          <div class="card-footer small text-muted">Actualizado {{time}}</div>
        </div>

      </div>
      <!-- /.container-fluid -->
{% endblock content %}

{% block scripts %}
<!-- Core plugin JavaScript-->
<script src="{% static '/js/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Page level plugin JavaScript-->
<script src="{% static '/js/chart.js/Chart.min.js' %}"></script>
<script src="{% static '/js/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static '/js/datatables/dataTables.bootstrap4.js' %}"></script>


<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin/sb-admin.min.js' %}"></script>
<script>
  var ejeX = []
  var ejeY = []
  var may = 0
  {% for gain in dataGraphic %}
    var val = {{ gain.1 }}
    ejeX.push("{{ gain.0|date:'D d M' }}")
    ejeY.push(val)
    if (may < val){
      may = val;
    }
  {% endfor %}
</script>
<!-- Demo scripts for this page-->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>
<script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
{% endblock scripts %}

apps/colaborator/templates/myservices.html
{% extends "colaborator/base.html" %}
{% load static %}
{% load humanize %}
{% load utilities %}
{% block styles %}
<link href="{% static '/css/colaborator.css' %}" rel="stylesheet">
{% endblock styles %}
{% block content %}
      <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
          </li>
          <li class="breadcrumb-item active">Mis servicios</li>
        </ol>
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-handshake"></i> Servicios prestados
            </div>
          <div class="card-body">
            {% if messages %}
            <div class="row">
              <div class="col-sm-12 col-md-8 offset-md-2">
                  {% for message in messages %}
                    <div class="alert alert-success">
                      <button type="button" class="close" data-dismiss="alert {{ message.tag }}">×</button>
                      {{ message|striptags }}
                    </div>
                  {% endfor %}
              </div>
            </div>
            {% endif %}
            <div class="table-responsive">
                <table class="table">
                    <thead class="thead-default">
                        <tr>
                            <th>#</th>
                            <th>Servicio</th>
                            <th>Descripción</th>
                            <th>Tipo de cobro</th>
                            <th>Tarifa</th>
                            <th>Ciudad</th>
                            <th colspan="2">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for service in object_list %}
                        <tr>
                            <th scope="row">{{ service.id }}</th>
                            <td>{{ service.service.name }}</td>
                            <td>{{ service.description }}</td>
                            <td>{{ typePay|get_item:service.rate_type }}</td>
                            <td>{{ service.rate }}</td>
                            <td>{{ service.coverage_city }}</td>
                            <td><a href="{% url 'colaborator:updateservice' pk=service.id %}"><i class="fas fa-fw fa-edit"></i></a></td>
                            <td><a href="#" class="deleteservice" data-urldelete="{% url 'colaborator:deleteservice' pk=service.id %}"><i class="fas fa-fw fa-trash"></i></a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="8"><a href="{% url 'colaborator:assingservice' %}"><button class="btn btn-primary">Asociarme un nuevo servicio</button></a></td>
                        </tr>
                        <tr>
                            <td colspan="8"><b>Nota:</b> Si considera que puede prestar un nuevo servicio que no esta listado y desea proponerlo, por favor envie un correo con una breve descripción a <a href="mailto:admin@dogenest.com">admin@dogenest.com</a> </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <div class="row text-rigth">
                <div class="col-1 offset-11">
                    <nav aria-label="Page navigation example">
                    {% if is_paginated %}
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                            {% endif %}

                            {% for i in paginator.page_range %}
                                <li {% if page_obj.number == i %} class="active" {% endif %} class="page-item">
                                    <a class="page-link" href="?page={{i}}">{{ i }}</a>
                                </li>
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <li><a class="page-link" href="?page={{ page_obj.next_page_number }}" class="page-item">&raquo;</a></li>
                            {% endif %}
                        </ul>
                    {% endif %}
                    </nav>
                </div>
            </div>
          </div>
          <div class="card-footer small text-muted">Actualizado {{time}}</div>
        </div>
      </div>
{% endblock content %}

{% block scripts %}
<!-- Core plugin JavaScript-->
<script src="{% static '/js/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Page level plugin JavaScript-->
<script src="{% static '/js/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static '/js/datatables/dataTables.bootstrap4.js' %}"></script>

<script src="{% static '/js/colaborator.js' %}"></script>
<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin/sb-admin.min.js' %}"></script>
<script>
  var ejeX = []
  var ejeY = []
  var may = 0
  {% for gain in dataGraphic %}
    var val = {{ gain.1 }}
    ejeX.push("{{ gain.0|date:'D d M' }}")
    ejeY.push(val)
    if (may < val){
      may = val;
    }
  {% endfor %}
</script>
<!-- Demo scripts for this page-->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>
{% endblock scripts %}

apps/colaborator/templates/registerColaborator.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block styles %}
    <link rel="stylesheet" href="{% static '/css/RegisterColaborator.css' %}">
{% endblock styles %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                 {% if form.errors %}
                    <div class="alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        {% for field in form %}
                            {% if field.errors %}
                                {{ field.errors|striptags }}
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center">Sign In</h5>
                        <form class="form-signin" method="post" role="form">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ next }}" />
                            <div class="form-label-group">
                                {{ form.username|add_class:'form-control' }} 
                                <label for="inputEmail">Username</label>
                            </div>

                            <div class="form-label-group">
                                {{ form.password|add_class:'form-control' }}
                                <label for="inputPassword">Password</label>
                            </div>

                            <button class="genric-btn success float-right large" type="submit">Sign in</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

apps/colaborator/templates/servicecolaborator.html
{% extends "colaborator/base.html" %}
{% load static %}
{% load humanize %}
{% load utilities %}
{% block styles %}
<link href="{% static '/css/colaborator.css' %}" rel="stylesheet">
{% endblock styles %}
{% block content %}
      <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
          </li>
          <li class="breadcrumb-item active">Asignando servicios</li>
        </ol>
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-plus-square"></i> Asignar servicio
            </div>
          <div class="card-body">
            <div class="col col-sm-12 col-md-8 offset-md-2">
              <form method="post" novalidate>
                  {% csrf_token %}
                  {% for field in form %}
                  <div class="form-group row">
                    <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-10">
                      {{ field }}
                      <span class="text-danger">{{ field.errors|striptags }}</span>
                    </div>
                  </div>
                  {% endfor %}
                  <div class="float-right">
                    <a href="{% url 'colaborator:myservices' %}"><button type="button" class="btn btn-danger">Cancelar</button></a>
                    <button type="submit" class="btn btn-primary">Guardar</button>
                  </div>
              </form>
            </div>
          </div>
          <div class="card-footer small text-muted"><b>Nota:</b> Si considera que puede prestar un nuevo servicio que no esta listado y desea proponerlo, por favor envie un correo con una breve descripción a <a href="mailto:admin@dogenest.com">admin@dogenest.com</a></div>
        </div>
      </div>
{% endblock content %}

{% block scripts %}
<!-- Core plugin JavaScript-->
<script src="{% static '/js/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Page level plugin JavaScript-->
<script src="{% static '/js/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static '/js/datatables/dataTables.bootstrap4.js' %}"></script>


<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin/sb-admin.min.js' %}"></script>
<script>
  var ejeX = []
  var ejeY = []
  var may = 0
  {% for gain in dataGraphic %}
    var val = {{ gain.1 }}
    ejeX.push("{{ gain.0|date:'D d M' }}")
    ejeY.push(val)
    if (may < val){
      may = val;
    }
  {% endfor %}
</script>
<!-- Demo scripts for this page-->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>
{% endblock scripts %}