apps/authenticate/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required
from .views import *


app_name = 'authenticate'

urlpatterns = [
    path('', LoginView.as_view(), name="login"),
    path('logout/', login_required(LogoutView.as_view()), name="logout"),
]

apps/colaborator/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required
from .views import *


app_name = 'colaborator'

urlpatterns = [
    path('', login_required(HomecolaboratorView.as_view()), name="home"),
    path('orders', login_required(OrdersColaboboratorView.as_view()), name="orders"),
    path('myservices', login_required(ServicesColaboratorView.as_view()), name="myservices"),
    path('assingservice', login_required(CreateServiceColaboratorView.as_view()), name="assingservice"),
    path('service/<int:pk>', login_required(UpdateServiceColaboratorView.as_view()), name="updateservice"),
    path('servicedelete/<int:pk>', login_required(DeleteServiceColaboratorView.as_view()), name="deleteservice")
]

apps/core/urls.py
from django.urls import path
from .views import *


app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('myprofile', MyProfile.as_view(), name="myprofile"),
    path('newuser/<slug:typeuser>', NewProfile.as_view(), name="newuser"),
]

mascotas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.core.urls')),
    path('admin/', admin.site.urls),
    path('authenticate/', include('apps.authenticate.urls')),
    path('colaborator/', include('apps.colaborator.urls')),
    path('customer/', include('apps.customer.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/colaborator/models.py
from django.db import models

# Create your models here.

class Colaborator(models.Model):
    idPerson   = models.IntegerField()
    name = models.CharField(max_length=50)
    mail = models.EmailField()
    experience = models.TextField()
    phone = models.CharField(max_length=12)
    address = models.TextField()
    qualification = models.IntegerField(default=5)
    date_of_birth = models.DateField()                    

apps/colaborator/forms.py
from django import forms
from apps.core.models import *

class ServicePerColaboratorForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(ServicePerColaboratorForm, self).__init__(*args, **kwargs)

    class Meta:
        model = ServicePerColaborator
        exclude = ['colaborator']

        fields = ('coverage_city', 'rate_type', 'pet_types', 'rate', 'description', 'service')
        widgets = {
            'coverage_city': forms.Select(attrs={
                'placeholder': 'Ciudad de cobertura',
                'class':'form-control'
            }),
            'rate_type': forms.Select(attrs={
                'placeholder': 'Ciudad de cobertura',
                'class':'form-control'
            }),
            'pet_types': forms.CheckboxSelectMultiple(attrs={
                
            }),
            'rate': forms.TextInput(attrs={
                'type' : 'text',
                'placeholder': 'Tarifa',
                'class':'form-control'
            }),
            'description': forms.Textarea(attrs={
                'class':'form-control',
                'placeholder': "Describa su servicio"
            }),
            'service': forms.Select(attrs={
                'placeholder': 'Servicio',
                'class':'form-control'
            }),
        }
        labels = {
            'coverage_city': "Ciudad de cobertura",
            'rate_type': "Tipo de cobro",
            'pet_types': "Tipo de mascota",
            'rate': "Tarifa",
            'description': "Descripción",
            'service': "Servicio",
        }

apps/colaborator/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views import View
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy, reverse
from apps.core.models import *
from apps.customer.models import *
from .forms import *
import datetime, datetime
from django.db.models import F
from django.db.models import Count, Sum
from django.db import connection
from django.core.exceptions import ValidationError
# Create your views here.

class HomecolaboratorView(TemplateView):
    template_name = "dashboard-collaborator.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = datetime.date.today()
        day = (today.weekday() + 6) % 7 #0 Dom #1 Lun #2 Mar...
        lastpay = today - datetime.timedelta(day)
        lastpay = datetime.datetime.combine(lastpay, datetime.time.min)  
        today = datetime.datetime.combine(today, datetime.time.max)  
        orders = Order.objects.filter(datetime_finally__range=(lastpay, today), service__colaborator=self.request.user, status='finalized').annotate(payColaborator=F('price') - F('utility'))
        newOrders = Order.objects.filter(service__colaborator=self.request.user, status='request').count()
        today_min = datetime.datetime.combine(datetime.date.today(), datetime.time.min)
        today_max = datetime.datetime.combine(datetime.date.today(), datetime.time.max)
        todayOrders = Order.objects.filter(service__colaborator=self.request.user, datetime_booking__range=(today_min, today_max), status='ready').annotate(payColaborator=F('price') - F('utility')).count()
        with connection.cursor() as cursor:
            queryToGraph = """select distinct(DATE(customer_order.datetime_finally)),sum(customer_order.price-customer_order.utility) 
                                from customer_order inner join core_servicepercolaborator on customer_order.service_id = core_servicepercolaborator.id 
                                where customer_order.status='finalized' 
                                and core_servicepercolaborator.colaborator_id = %s
                                group by DATE(customer_order.datetime_finally)
                                order by date ASC""" % self.request.user.id
            cursor.execute(queryToGraph)
            context["dataGraphic"] = cursor.fetchall()
        
        context["ordersThisWeek"] = orders
        context["countNewOrders"] = newOrders
        context["countTodayOrders"] = todayOrders
        context["time"] = datetime.datetime.now()
        return context

class OrdersColaboboratorView(ListView):
    def get_queryset(self, **kwargs):
        if 'filter' in self.request.GET:
            fil = self.request.GET.get('filter')
            if fil == 'news':
                queryset = Order.objects.filter(service__colaborator=self.request.user, status='request').annotate(payColaborator=F('price') - F('utility'))
            elif fil == 'today':
                today_min = datetime.datetime.combine(datetime.date.today(), datetime.time.min)
                today_max = datetime.datetime.combine(datetime.date.today(), datetime.time.max)
                queryset = Order.objects.filter(service__colaborator=self.request.user, datetime_booking__range=(today_min, today_max)).annotate(payColaborator=F('price') - F('utility')).order_by('id')
        else:
            queryset = Order.objects.filter(service__colaborator=self.request.user).order_by('status').annotate(payColaborator=F('price') - F('utility'))
        return queryset
    
    def get_context_data(self, **kwargs):
        statusOrders = {
            'request':'Solicitado',
            'accepted':'Aceptado',
            'waitpayment':'Esperando pago',
            'rejected':'Rechazado',
            'ready': 'Listo para iniciar',
            'expired':'Expirado',
            'inprogress':'Iniciado',
            'revertPay': 'Declinado, reversar pago',
            'finalized':'Finalizado'
        }
        context = super().get_context_data(**kwargs)
        context["titleTable"] = "test"
        context["status"] = statusOrders
        context["time"] = datetime.datetime.now()
        return context
    
    def post(self, request, *args, **kwargs):
        queryget = ""
        if 'filter' in self.request.GET:
            queryget = "?filter=%s" % self.request.GET.get('filter')       

        order= get_object_or_404(Order, pk=request.POST.get('id'), service__colaborator=request.user)
        order.status = request.POST.get('status')
        if order.status == 'finalized':
            order.datetime_finally = datetime.datetime.now()
        order.save()
        return redirect(reverse('colaborator:orders') + queryget)

class ServicesColaboratorView(ListView):
    template_name = 'myservices.html'
    paginate_by = 15
    def get_queryset(self):
        queryset = ServicePerColaborator.objects.filter(colaborator=self.request.user).order_by('id')
        return queryset

    def get_context_data(self, **kwargs):
        typePay = {
            'hours':'Horas',
            'full':'Tarifa unica',
        }
        context = super(ServicesColaboratorView, self).get_context_data(**kwargs)
        context["typePay"] = typePay
        context["time"] = datetime.datetime.now()
        return context

class CreateServiceColaboratorView(SuccessMessageMixin, CreateView):
    model = ServicePerColaborator
    form_class = ServicePerColaboratorForm
    template_name = 'servicecolaborator.html'
    success_message = '¡Se ha asignado un nuevo servicio en su cuenta!'
    
    def get_success_url(self):
        return reverse('colaborator:myservices')
    
    def get_context_data(self, **kwargs):
        context = super(CreateServiceColaboratorView, self).get_context_data(**kwargs)
        context["time"] = datetime.datetime.now()
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.colaborator = self.request.user

        try:
            self.object.full_clean()
        except ValidationError:
            #raise ValidationError("No can do, you have used this name before!")
            #return self.form_invalid(form)
            form._errors["service"] = "Este servicio ya esta siendo prestado por ud. por favor edite su actual servicio."
            return super(CreateServiceColaboratorView, self).form_invalid(form)
        return super(CreateServiceColaboratorView, self).form_valid(form)
    
class UpdateServiceColaboratorView(UpdateView):
    model = ServicePerColaborator
    form_class = ServicePerColaboratorForm
    template_name = 'servicecolaborator.html'
    success_message = '¡Se ha actualizado el servicio en su cuenta!'
    
    def get_success_url(self):
        return reverse('colaborator:myservices')

class DeleteServiceColaboratorView(DeleteView):
    model = ServicePerColaborator
    
    def get(self, request, pk):
        service = get_object_or_404(ServicePerColaborator, pk=pk)
        service.delete()
        return redirect(reverse('colaborator:myservices'))

apps/colaborator/templates/colaborator/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% load bootstrap4 %}
{% get_current_language as LANGUAGE_CODE %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> 
<html class="no-js" lang="{{ LANGUAGE_CODE }}"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>{% block title %}{% endblock title %}</title>

        <!-- Custom fonts for this template-->
        <link href="{% static '/css/fontawesome-free/all.min.css' %}" rel="stylesheet" type="text/css">

        <!-- Page level plugin CSS-->
        <link href="{% static '/css/datatable/dataTables.bootstrap4.css' %}" rel="stylesheet">

        <!-- Custom styles for this template-->
        <link href="{% static '/css/sbadmin/sb-admin.css' %}" rel="stylesheet">
        {% block styles %}
        
        {% endblock styles %}
    </head>
    <body id="page-top">
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        {% block header %}
        <header>
            <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

                <a class="navbar-brand mr-1" href="{% url 'colaborator:home' %}">Dogesnet</a>

                <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
                <i class="fas fa-bars"></i>
                </button>

                <!-- Navbar -->
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown no-arrow">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user-circle fa-fw"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="{% url 'core:myprofile' %}">Mi perfíl</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Cerrar Sesión</a>
                        </div>
                    </li>
                </ul>
            </nav>
        </header>
        {% endblock header %}
        <div id="wrapper">
            {% block sidebar %}
            <!-- Sidebar -->
                <ul class="sidebar navbar-nav">
                <li class="nav-item {% if request.resolver_match.url_name == "home" %}active{% endif %}">
                    <a class="nav-link" href="{% url 'colaborator:home' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                    </a>
                </li>
                <li class="nav-item {% if request.resolver_match.url_name == "orders" %}active{% endif %}">
                    <a class="nav-link" href="{% url 'colaborator:orders' %}">
                    <i class="fas fa-fw fa-list"></i>
                    <span>Ordenes</span></a>
                </li>
                <li class="nav-item {% if request.resolver_match.url_name == "myservices" %}active{% endif %}">
                    <a class="nav-link" href="{% url 'colaborator:myservices' %}">
                    <i class="fas fa-fw fa-handshake"></i>
                    <span>Servicios</span></a>
                </li>
                
                <!--<li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Pages</span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                    <h6 class="dropdown-header">Login Screens:</h6>
                    <a class="dropdown-item" href="login.html">Login</a>
                    <a class="dropdown-item" href="register.html">Register</a>
                    <a class="dropdown-item" href="forgot-password.html">Forgot Password</a>
                    <div class="dropdown-divider"></div>
                    <h6 class="dropdown-header">Other Pages:</h6>
                    <a class="dropdown-item" href="404.html">404 Page</a>
                    <a class="dropdown-item" href="blank.html">Blank Page</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="charts.html">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Charts</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="tables.html">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Tables</span></a>
                </li>-->
                </ul>
            {% endblock sidebar %}
            <div id="content-wrapper">
            {% block content %}
            {% endblock content %}
                
                <!-- Sticky Footer -->
                <footer class="sticky-footer">
                    <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright © Your Website 2019</span>
                    </div>
                    </div>
                </footer>
            </div>
        </div>
        {% block footer %}
          <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>

        <!-- Logout Modal-->
        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Seguro que quieres salir?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                </div>
                <div class="modal-body">Seleccione Logout para terminar la sesión actual.</div>
                <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                <a class="btn btn-primary" href="{% url 'authenticate:logout' %}">Cerrar sesión</a>
                </div>
            </div>
            </div>
        </div>
        {% endblock footer %}
        {% bootstrap_javascript jquery='full' %}
        {% block scripts %}
        
        {% endblock scripts %}
    </body>
</html>